import Head from 'next/head'
import Image from "next/image";

import styles from "@/styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen flex justify-center  bg-black">
        <div className="max-w-7xl mx-auto pt-10 flex flex-col">
          <Link
            href="/projects"
            className="text-4xl font-black text-white hover:text-green-500"
          >
            Projects
          </Link>
          <br />
          <span className="text-white text-center">(Click Me)</span>
        </div>
      </main>
    </>
  );
}
